name: Check connection

on:
  workflow_dispatch:
    inputs:
      url:
        description: "URL to test"
        required: true
        type: string

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check connection
        run: |
          curl -I "${{ github.event.inputs.url }}" || exit
